model: yolov5s-cls.pt
data: data
epochs: 50
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: '0'
workers: 8
project: runs/train-cls
name: skin_lesion_cls_gpu
exist_ok: true
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: runs\train-cls\skin_lesion_cls_gpu
